services:
  famedly-sync-agent:
    image: registry.famedly.net/docker-oss/famedly-sync-agent:latest
    volumes:
      - type: bind
        source: ./opt
        target: /opt/famedly-sync
    network_mode: host
