apiVersion: batch/v1
kind: CronJob
metadata:
  name: ldap-sync
  namespace: ldap-sync
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ldap-sync
              image: registry.famedly.net/docker-oss/famedly-sync-agent:v0.4.0
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /opt/famedly-sync/
                  name: famedly-sync-config
          restartPolicy: OnFailure
          volumes:
            - name: famedly-sync-config
              configMap:
                name: famedly-sync
