name: Release

on:
  push:
    tags:
      # For root tags, such as v0.4.2
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      # For subfolder tags, such as workflow-engine-v1.18.0
      #- "[a-zA-Z-_]+v[0-9]+.[0-9]+.[0-9]+"
      #- "[a-zA-Z-_]+v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            asset_name: ${{ github.event.repository.name }}-linux-amd64-latest
          - platform: linux/arm64
            runner: arm-ubuntu-latest-8core
            asset_name: ${{ github.event.repository.name }}-linux-aarch64-latest
    runs-on: ${{ matrix.runner }}
    container: registry.famedly.net/docker-oss/rust-container:nightly@sha256:ae9a782f906641972b0ab95886e30cfa444899c75b5e6368c0f59ffc755f95c8
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Rust
        uses: famedly/backend-build-workflows/.github/actions/rust-prepare@main
        with:
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}

      - name: Caching
        uses: Swatinem/rust-cache@cb8ffc21fa260a61d7c314b390985a11fcddf81a
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install additional cargo tooling
        uses: taiki-e/cache-cargo-install-action@c3a809e766eccfe7ffbd1c87907d83b26ac07e5b
        with:
          tool: cargo-auditable

      - name: Build release
        shell: bash
        run: cargo auditable build --release

      - name: Rename binary
        shell: bash
        run: "mv target/release/${{ github.event.repository.name }} target/release/${{ matrix.asset_name }}"

      - name: Attest
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1
        with:
          subject-path: '${{ github.workspace }}/target/release/${{ matrix.asset_name }}'

      - name: Upload binary
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: release-${{ matrix.asset_name }}
          path: '${{ github.workspace }}/target/release/${{ matrix.asset_name }}'

  sbom:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    container: registry.famedly.net/docker-oss/rust-container:nightly@sha256:ae9a782f906641972b0ab95886e30cfa444899c75b5e6368c0f59ffc755f95c8
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Rust
        uses: famedly/backend-build-workflows/.github/actions/rust-prepare@main
        with:
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}

      - name: Caching
        uses: Swatinem/rust-cache@cb8ffc21fa260a61d7c314b390985a11fcddf81a
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install cargo-sbom
        uses: taiki-e/cache-cargo-install-action@c3a809e766eccfe7ffbd1c87907d83b26ac07e5b
        with:
          tool: cargo-sbom

      - name: Install cyclonedx-rust-cargo
        uses: taiki-e/cache-cargo-install-action@c3a809e766eccfe7ffbd1c87907d83b26ac07e5b
        with:
          tool: cargo-cyclonedx

      - name: Generate SPDX SBOM
        shell: bash
        run: 'cargo sbom > ${{ github.event.repository.name }}.spdx.json'
      - name: Generate CycloneDX SBOM
        shell: bash
        run: cargo cyclonedx -f json

      - name: Attest SPDX SBOM
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1
        with:
          subject-path: '${{ github.workspace }}/${{ github.event.repository.name }}.spdx.json'
      - name: Attest CycloneDX SBOM
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1
        with:
          subject-path: '${{ github.workspace }}/${{ github.event.repository.name }}.cdx.json'

      - name: Upload SPDX SBOM
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: release-sbom-spdx
          path: '${{ github.workspace }}/${{ github.event.repository.name}}.spdx.json'
      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: release-sbom-cdx
          path: '${{ github.workspace }}/${{ github.event.repository.name }}.cdx.json'

  release:
    runs-on: ubuntu-latest
    needs: [build, sbom]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: release-*
          path: artifacts
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@fbadcc90e88ecface60a0a0d123795b784ceb239
        with:
          files: artifacts/*
          prerelease: "${{ contains(github.ref_name, 'rc') }}"
          generate_release_notes: true
