name: Release

on:
  push:
    tags:
      # For root tags, such as v0.4.2
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      # For subfolder tags, such as workflow-engine-v1.18.0
      #- "[a-zA-Z-_]+v[0-9]+.[0-9]+.[0-9]+"
      #- "[a-zA-Z-_]+v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            asset_name: ${{ github.event.repository.name }}-linux-amd64-latest
          - platform: linux/arm64
            runner: arm-ubuntu-latest-8core
            asset_name: ${{ github.event.repository.name }}-linux-aarch64-latest
    runs-on: ${{ matrix.runner }}
    container: registry.famedly.net/docker-oss/rust-container:nightly@sha256:8edf583411ee94100b14f53f621edd9d6e05c895a3fbaee3046e4f2f70f89195
    steps:
      - name: Checkout code
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Set up Rust
        uses: famedly/backend-build-workflows/.github/actions/rust-prepare@fcc2ec82a725d5c4c9c6a8f19e8df101c178dcb6
        with:
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}

      - name: Caching
        uses: Swatinem/rust-cache@65012b490220f477f20ab979e35ae732e6de4e68
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install additional cargo tooling
        uses: taiki-e/cache-cargo-install-action@50baf549964a2319a419344c87f6a2141748e7f5
        with:
          tool: cargo-auditable

      - name: Build release
        shell: bash
        run: cargo auditable build --release

      - name: Rename binary
        shell: bash
        run: "mv target/release/${{ github.event.repository.name }} target/release/${{ matrix.asset_name }}"

      - name: Attest
        uses: actions/attest-build-provenance@10334b5f1e684784025c3fc0a277c88c19089275
        with:
          subject-path: '${{ github.workspace }}/target/release/${{ matrix.asset_name }}'

      - name: Upload binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: release-${{ matrix.asset_name }}
          path: '${{ github.workspace }}/target/release/${{ matrix.asset_name }}'

  sbom:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    container: registry.famedly.net/docker-oss/rust-container:nightly@sha256:8edf583411ee94100b14f53f621edd9d6e05c895a3fbaee3046e4f2f70f89195
    steps:
      - name: Checkout code
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Set up Rust
        uses: famedly/backend-build-workflows/.github/actions/rust-prepare@fcc2ec82a725d5c4c9c6a8f19e8df101c178dcb6
        with:
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}

      - name: Caching
        uses: Swatinem/rust-cache@65012b490220f477f20ab979e35ae732e6de4e68
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install cargo-sbom
        uses: taiki-e/cache-cargo-install-action@50baf549964a2319a419344c87f6a2141748e7f5
        with:
          tool: cargo-sbom

      - name: Install cyclonedx-rust-cargo
        uses: taiki-e/cache-cargo-install-action@50baf549964a2319a419344c87f6a2141748e7f5
        with:
          tool: cargo-cyclonedx

      - name: Generate SPDX SBOM
        shell: bash
        run: 'cargo sbom > ${{ github.event.repository.name }}.spdx.json'
      - name: Generate CycloneDX SBOM
        shell: bash
        run: cargo cyclonedx -f json

      - name: Attest SPDX SBOM
        uses: actions/attest-build-provenance@10334b5f1e684784025c3fc0a277c88c19089275
        with:
          subject-path: '${{ github.workspace }}/${{ github.event.repository.name }}.spdx.json'
      - name: Attest CycloneDX SBOM
        uses: actions/attest-build-provenance@10334b5f1e684784025c3fc0a277c88c19089275
        with:
          subject-path: '${{ github.workspace }}/${{ github.event.repository.name }}.cdx.json'

      - name: Upload SPDX SBOM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: release-sbom-spdx
          path: '${{ github.workspace }}/${{ github.event.repository.name}}.spdx.json'
      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: release-sbom-cdx
          path: '${{ github.workspace }}/${{ github.event.repository.name }}.cdx.json'

  release:
    runs-on: ubuntu-latest
    needs: [build, sbom]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317
        with:
          pattern: release-*
          path: artifacts
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@403a5240f3837fa857f642062e05aad6bb3391ca
        with:
          files: artifacts/*
          prerelease: "${{ contains(github.ref_name, 'rc') }}"
          generate_release_notes: true
