name: Rust workflow

# Trigger the CI on any tags, pushes to any branch and PRs to any branch.
on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Defined CI jobs.
jobs:
  tests:
    uses: famedly/backend-build-workflows/.github/workflows/rust-workflow.yml@ccb800fdb716ff3b8459f19bb9ceb56544d0798e
    secrets: inherit
